FROM python:3.10

WORKDIR /app


# Copy everything early (bad: includes dev files, invalidates cache)
COPY . .


# Install dependencies (this creates a big layer)
RUN pip install --no-cache-dir -r requirements.txt


CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
